# EDA (Análise Exploratória de Dados)

In [1]:
import pandas as pd
from phishing import config

raw = pd.read_csv(config.RAW_CSV)

print("Shape: ", raw.shape)

# 1. Ausentes
print("Ausentes:", raw.isna().sum().sum())
# 2. Tipos
print("Tipos:", dict(raw.dtypes.value_counts().astype(int)))

# 3. Duplicatas — ignorando o id, que é único por construção
dups = raw.drop(columns=[config.ID_COLUMN]).duplicated().sum()
print(f"Linhas duplicadas: {dups}")

# 4. Colunas constantes
const = [c for c in raw.columns if raw[c].nunique() <= 1]
print("Colunas constantes:", const)

# 5. Balanceamento
print(raw[config.TARGET].value_counts())

Shape:  (10000, 50)
Ausentes: 0
Tipos: {dtype('int64'): np.int64(47), dtype('float64'): np.int64(3)}
Linhas duplicadas: 419
Colunas constantes: ['HttpsInHostname']
CLASS_LABEL
1    5000
0    5000
Name: count, dtype: int64

In [2]:
raw

,id,NumDots,SubdomainLevel,PathLevel,UrlLength,NumDash,NumDashInHostname,AtSymbol,TildeSymbol,NumUnderscore,...,IframeOrFrame,MissingTitle,ImagesOnlyInForm,SubdomainLevelRT,UrlLengthRT,PctExtResourceUrlsRT,AbnormalExtFormActionR,ExtMetaScriptLinkRT,PctExtNullSelfRedirectHyperlinksRT,CLASS_LABEL
0,1,3,1,5,72,0,0,0,0,0,...,0,0,1,1,0,1,1,-1,1,1
1,2,3,1,3,144,0,0,0,0,2,...,0,0,0,1,-1,1,1,1,1,1
2,3,3,1,2,58,0,0,0,0,0,...,0,0,0,1,0,-1,1,-1,0,1
3,4,3,1,6,79,1,0,0,0,0,...,0,0,0,1,-1,1,1,1,-1,1
4,5,3,0,4,46,0,0,0,0,0,...,1,0,0,1,1,-1,0,-1,-1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,3,1,1,50,0,0,0,0,0,...,0,0,0,1,1,-1,1,0,1,0
9996,9997,2,1,4,59,1,0,0,0,0,...,1,0,0,1,0,0,1,0,1,0
9997,9998,2,1,4,57,0,0,0,0,0,...,0,0,0,1,0,1,1,0,1,0
9998,9999,3,1,1,49,0,0,0,0,0,...,1,0,0,1,1,0,1,0,1,0
9999,10000,3,1,2,52,3,0,0,0,0,...,0,0,0,1,1,1,1,1,1,0

In [4]:
from phishing import data

df_limpo, audit = data.clean(raw)

df_limpo

,NumDots,SubdomainLevel,PathLevel,UrlLength,NumDash,NumDashInHostname,AtSymbol,TildeSymbol,NumUnderscore,NumPercent,...,IframeOrFrame,MissingTitle,ImagesOnlyInForm,SubdomainLevelRT,UrlLengthRT,PctExtResourceUrlsRT,AbnormalExtFormActionR,ExtMetaScriptLinkRT,PctExtNullSelfRedirectHyperlinksRT,CLASS_LABEL
0,3,1,5,72,0,0,0,0,0,0,...,0,0,1,1,0,1,1,-1,1,1
1,3,1,3,144,0,0,0,0,2,0,...,0,0,0,1,-1,1,1,1,1,1
2,3,1,2,58,0,0,0,0,0,0,...,0,0,0,1,0,-1,1,-1,0,1
3,3,1,6,79,1,0,0,0,0,0,...,0,0,0,1,-1,1,1,1,-1,1
4,3,0,4,46,0,0,0,0,0,0,...,1,0,0,1,1,-1,0,-1,-1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9576,3,1,1,50,0,0,0,0,0,0,...,0,0,0,1,1,-1,1,0,1,0
9577,2,1,4,59,1,0,0,0,0,0,...,1,0,0,1,0,0,1,0,1,0
9578,2,1,4,57,0,0,0,0,0,0,...,0,0,0,1,0,1,1,0,1,0
9579,3,1,1,49,0,0,0,0,0,0,...,1,0,0,1,1,0,1,0,1,0
9580,3,1,2,52,3,0,0,0,0,0,...,0,0,0,1,1,1,1,1,1,0

In [7]:
X_train, X_test, y_train, y_test = data.split(df_limpo)