In [1]:
import pandas as pd 
df = pd.read_csv('../data/raw/url_dataset_full.csv')
df.head()

,qty_dot_url,qty_hyphen_url,qty_underline_url,qty_slash_url,qty_questionmark_url,qty_equal_url,qty_at_url,qty_and_url,qty_exclamation_url,qty_space_url,...,qty_ip_resolved,qty_nameservers,qty_mx_servers,ttl_hostname,tls_ssl_certificate,qty_redirects,url_google_index,domain_google_index,url_shortened,phishing
0,3,0,0,1,0,0,0,0,0,0,...,1,2,0,892,0,0,0,0,0,1
1,5,0,1,3,0,3,0,2,0,0,...,1,2,1,9540,1,0,0,0,0,1
2,2,0,0,1,0,0,0,0,0,0,...,1,2,3,589,1,0,0,0,0,0
3,4,0,2,5,0,0,0,0,0,0,...,1,2,0,292,1,0,0,0,0,1
4,2,0,0,0,0,0,0,0,0,0,...,1,2,1,3597,0,1,0,0,0,0

In [6]:
df.shape

(88647, 112)

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88647 entries, 0 to 88646
Columns: 112 entries, qty_dot_url to phishing
dtypes: float64(1), int64(111)
memory usage: 75.7 MB

In [3]:
df['phishing'].value_counts(normalize=True)

phishing
0    0.65428
1    0.34572
Name: proportion, dtype: float64

In [9]:
df.groupby('phishing')['directory_length'].describe()

            count       mean        std  min   25%   50%   75%     max
phishing
0         58000.0   1.551828  10.305146 -1.0  -1.0  -1.0  -1.0   530.0
1         30647.0  28.469214  32.255140 -1.0  10.0  23.0  39.0  1286.0

In [12]:
(df['directory_length'] == -1).groupby(df['phishing']).mean()

phishing
0    0.806241
1    0.024374
Name: directory_length, dtype: float64